### ISSUE TITLE
1番目の引数でsubject idを取得したい

### ISSUE THREAD

**Issue by miminashi** [realglobe-Inc/v-daemon#7]
呼び出される側のコマンドライン引数は、

```
verb object1 object2...
```

のようになっているが、

```
subject verb object1 object2...
```

となっているほうが、サブジェクト名を管理する手間が省けて良い気がします。

**Comment by okunishinishi** [comment]
@miminashi 対応しました。Breaking changeなのでmajor versionをあげました。npm updateだと多分更新されないので、

```bash 
npm i v-daemon@2 -g
```

で明示的に上げる必要があります
